### ISSUE TITLE
META - PyData NYC 2023 Prep

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/big-data-tutorial-90min#2]
```[tasklist]
### Tasks
- [x] Inital trim to condense material
- [x] Check content and code, test on Nebari
- [x] Update navigation links
- [x] Verify Dask cluster is setup once at the begining & shutdown at the very end in NB flow
- [x] Set-up Nebari instance for the tutorial (enable Dask access for participants)
- [x] Update 00-introduction with Nebari instance and presenter info
- [x] Remove Panel NB & add callout in hv plot NB
- [x] Verify environments
```

**Comment by pavithraes** [comment]
Closing as complete!
